# Generated by Django 2.2.3 on 2019-11-29 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarTransaksi',
            fields=[
                ('nomor', models.AutoField(primary_key=True, serialize=False)),
                ('produk_jumlah', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('subtotal', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('transaksi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.DaftarTransaksi')),
            ],
        ),
        migrations.CreateModel(
            name='DaftarBarang',
            fields=[
                ('nomor', models.AutoField(primary_key=True, serialize=False)),
                ('nama_product', models.CharField(max_length=40)),
                ('jumlah_produk', models.IntegerField()),
                ('unit_produk', models.IntegerField(blank=True, null=True)),
                ('harga_beli_satuan', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_harga_beli', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('laba_persen', models.IntegerField()),
                ('harga_jual_satuan', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('subtotal_harga_jual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
