# Generated by Django 2.2.3 on 2019-08-14 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='profile_picture.png', upload_to='profile_pictures')),
                ('nama_depan', models.CharField(blank=True, max_length=20)),
                ('nama_belakang', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('nomor_telephone', models.IntegerField(blank=True, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kode_pos', models.IntegerField(blank=True, null=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
